# Generated by Django 5.2.7 on 2025-10-20 11:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_serviceinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Client's full name", max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Primary contact email address', max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Work Email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=20, verbose_name='Phone Number')),
                ('company_name', models.CharField(help_text='Name of the organization', max_length=200, verbose_name='Company/Business Name')),
                ('job_title', models.CharField(blank=True, help_text="Client's position in the company", max_length=150, verbose_name='Job Title')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=50, verbose_name='Company Size')),
                ('country', models.CharField(help_text='Country or region of operation', max_length=100, verbose_name='Country/Region')),
                ('project_type', models.CharField(help_text='Type of project or service needed', max_length=100, verbose_name='Project Type')),
                ('project_description', models.TextField(help_text='Detailed description of project requirements', verbose_name='Project Description')),
                ('timeline', models.CharField(choices=[('urgent', 'ASAP (1-2 weeks)'), ('soon', 'Soon (2-4 weeks)'), ('flexible', 'Flexible (1-2 months)'), ('planned', 'Planned (3+ months)')], help_text='When the project needs to be completed', max_length=50, verbose_name='Project Timeline')),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under $5,000'), ('5k_10k', '$5,000 - $10,000'), ('10k_25k', '$10,000 - $25,000'), ('25k_50k', '$25,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('100k+', '$100,000+')], help_text='Approximate budget for the project', max_length=50, verbose_name='Budget Range')),
                ('additional_notes', models.TextField(blank=True, help_text="Any other information you'd like to share", verbose_name='Additional Notes')),
                ('reference_url', models.URLField(blank=True, help_text='Link to inspiration or similar projects', max_length=500, verbose_name='Reference URL')),
                ('how_did_you_hear', models.CharField(blank=True, choices=[('search', 'Search Engine'), ('social', 'Social Media'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=100, verbose_name='How did you hear about us?')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('converted', 'Converted'), ('declined', 'Declined')], default='new', max_length=50, verbose_name='Inquiry Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority Level')),
                ('is_spam', models.BooleanField(default=False, verbose_name='Marked as Spam')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='First Contact Date')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team member handling this inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('service', models.ForeignKey(blank=True, help_text='Primary service the client is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to='services.service', verbose_name='Service of Interest')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_contac_created_cb5667_idx'), models.Index(fields=['status', '-created_at'], name='core_contac_status_0490b6_idx'), models.Index(fields=['email'], name='core_contac_email_152524_idx'), models.Index(fields=['is_spam', '-created_at'], name='core_contac_is_spam_0cbaa9_idx')],
            },
        ),
    ]
