# Generated by Django 5.2.7 on 2025-10-19 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the service category', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the name', max_length=120, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', verbose_name='Description')),
                ('icon_class', models.CharField(default='fas fa-cog', help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='services_ca_slug_275513_idx'), models.Index(fields=['is_active', 'display_order'], name='services_ca_is_acti_8aac35_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the service', max_length=200, verbose_name='Service Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the title', max_length=220, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(help_text='Brief description for service cards (max 250 chars)', max_length=250, verbose_name='Short Description')),
                ('full_description', models.TextField(help_text='Detailed description of the service', verbose_name='Full Description')),
                ('image_url', models.URLField(help_text='Full URL to service image (hosted externally)', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Image URL')),
                ('icon_class', models.CharField(default='fas fa-laptop-code', help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50, verbose_name='FontAwesome Icon Class')),
                ('price_starting_at', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for this service (optional)', max_digits=10, null=True, verbose_name='Starting Price')),
                ('delivery_time_days', models.PositiveIntegerField(blank=True, help_text='Typical delivery timeframe in days (optional)', null=True, verbose_name='Delivery Time (Days)')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features (stored as JSON array)', verbose_name='Features List')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which services appear (lower numbers first)', verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this service on the homepage', verbose_name='Featured Service')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is visible on the website', verbose_name='Active')),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO (leave blank to use service title)', max_length=60, verbose_name='SEO Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO (max 160 chars)', max_length=160, verbose_name='SEO Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this service belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'display_order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'), models.Index(fields=['category', 'is_active', 'display_order'], name='services_se_categor_e11566_idx'), models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx')],
            },
        ),
    ]
