# Generated by Django 5.2.7 on 2025-10-19 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Client's full name", max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Optional: Contact phone number', max_length=20, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, help_text='Optional: Company or organization name', max_length=200, verbose_name='Company Name')),
                ('project_type', models.CharField(help_text='Type of project (e.g., Website, E-Commerce, Web App)', max_length=100, verbose_name='Project Type')),
                ('project_description', models.TextField(help_text='Detailed description of the project requirements', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Project Description')),
                ('budget_range', models.CharField(choices=[('under_5k', 'Under $5,000'), ('5k_10k', '$5,000 - $10,000'), ('10k_25k', '$10,000 - $25,000'), ('25k_50k', '$25,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('over_100k', 'Over $100,000'), ('not_sure', 'Not Sure Yet')], help_text='Approximate budget for the project', max_length=20, verbose_name='Budget Range')),
                ('timeline', models.CharField(choices=[('asap', 'ASAP (2-4 weeks)'), ('flexible', 'Flexible (1-2 months)'), ('planned', 'Planned (3+ months)'), ('ongoing', 'Ongoing Project')], help_text='When they need the project completed', max_length=20, verbose_name='Desired Timeline')),
                ('reference_url', models.URLField(blank=True, help_text='Optional: URL of similar websites or inspiration', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Reference/Inspiration URL')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information or requirements', verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('declined', 'Declined'), ('spam', 'Spam')], default='new', help_text='Current status of this inquiry', max_length=20, verbose_name='Inquiry Status')),
                ('assigned_to', models.CharField(blank=True, help_text='Team member handling this inquiry', max_length=100, verbose_name='Assigned To')),
                ('internal_notes', models.TextField(blank=True, help_text='Private notes for internal team use only', verbose_name='Internal Notes')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Internal estimate of project value', max_digits=10, null=True, verbose_name='Estimated Project Value')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submission', null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, help_text='Page that referred to the inquiry form', max_length=500, verbose_name='Referrer')),
                ('is_spam', models.BooleanField(default=False, help_text='Flag suspicious submissions', verbose_name='Marked as Spam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('contacted_at', models.DateTimeField(blank=True, help_text='When we first contacted the client', null=True, verbose_name='First Contact Date')),
                ('service', models.ForeignKey(blank=True, help_text="Specific service they're inquiring about (if any)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='services.service', verbose_name='Interested Service')),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='services_se_status_f7849b_idx'), models.Index(fields=['email'], name='services_se_email_eaf6d5_idx'), models.Index(fields=['is_spam', 'status'], name='services_se_is_spam_d5d403_idx'), models.Index(fields=['-created_at'], name='services_se_created_ce6273_idx')],
            },
        ),
    ]
