# Generated by Django 5.2.7 on 2025-12-03 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the blog category', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the name', max_length=120, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', verbose_name='Description')),
                ('icon_class', models.CharField(default='fas fa-folder', help_text="FontAwesome icon class (e.g., 'fas fa-laptop-code')", max_length=50, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which categories appear (lower numbers first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is visible on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx'), models.Index(fields=['is_active', 'display_order'], name='blog_catego_is_acti_fec796_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique tag name', max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the name', max_length=60, unique=True, verbose_name='URL Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is visible on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='blog_tag_slug_915fc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200, verbose_name='Post Title')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the title', max_length=220, unique=True, verbose_name='URL Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary for post previews (max 500 chars)', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(help_text='Full post content (supports HTML)', verbose_name='Content')),
                ('featured_image_url', models.URLField(blank=True, help_text='Full URL to featured image (hosted externally)', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Featured Image URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', help_text='Publishing status of this post', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was/will be published', null=True, verbose_name='Published Date')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this post on the blog homepage', verbose_name='Featured Post')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow readers to comment on this post', verbose_name='Allow Comments')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed', verbose_name='View Count')),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO (leave blank to use post title)', max_length=60, verbose_name='SEO Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO (max 160 chars)', max_length=160, verbose_name='SEO Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of this post', on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(help_text='Primary category for this post', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for this post', related_name='posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text="Commenter's name", max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('author_email', models.EmailField(help_text="Commenter's email (not displayed publicly)", max_length=254, verbose_name='Email Address')),
                ('author_website', models.URLField(blank=True, help_text="Optional: Commenter's website", verbose_name='Website')),
                ('content', models.TextField(help_text='Comment content', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='pending', help_text='Moderation status', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Parent Comment')),
                ('post', models.ForeignKey(help_text='The post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'status', '-created_at'], name='blog_commen_post_id_c9b05a_idx'), models.Index(fields=['status', '-created_at'], name='blog_commen_status_3c3297_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status', '-published_at'], name='blog_post_categor_f4a876_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-published_at'], name='blog_post_author__3a3e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', 'status'], name='blog_post_is_feat_203193_idx'),
        ),
    ]
